# Generated by Django 3.2.7 on 2021-09-25 12:34

import api.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('about', models.TextField()),
                ('address', models.TextField()),
                ('admission_ticket', models.TextField(blank=True)),
                ('images', djongo.models.fields.ArrayField(model_container=api.models.Image)),
                ('open_time', models.TextField(blank=True)),
                ('suggested_duration', models.TextField(blank=True)),
            ],
        ),
    ]
