# Generated by Django 3.2.7 on 2021-10-12 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211012_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='number_voting',
            field=models.TextField(default=0),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='rating_score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='city',
            name='number_voting',
            field=models.TextField(default=0),
        ),
        migrations.AlterField(
            model_name='city',
            name='rating_score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='nation',
            name='number_voting',
            field=models.TextField(default=0),
        ),
        migrations.AlterField(
            model_name='nation',
            name='rating_score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='number_voting',
            field=models.TextField(default=0),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='rating_score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='stay',
            name='number_voting',
            field=models.TextField(default=0),
        ),
        migrations.AlterField(
            model_name='stay',
            name='rating_score',
            field=models.FloatField(default=0),
        ),
    ]
