# Generated by Django 3.2.7 on 2021-09-25 14:33

import api.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('open_time', models.TextField()),
                ('phone', models.TextField()),
                ('website', models.TextField()),
                ('details', djongo.models.fields.EmbeddedField(model_container=api.models.RestaurantDetails)),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantDetails',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('cuisines', models.TextField()),
                ('meals', models.TextField()),
                ('special_diets', models.TextField()),
            ],
        ),
    ]
