# Generated by Django 3.2.7 on 2021-10-22 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_auto_20211012_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attractions', to='api.city'),
        ),
        migrations.AlterField(
            model_name='attraction_image',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.attraction'),
        ),
        migrations.AlterField(
            model_name='attraction_voting',
            name='item_vote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votings', to='api.attraction'),
        ),
        migrations.AlterField(
            model_name='attraction_voting',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attraction_votings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='city',
            name='nation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='api.nation'),
        ),
        migrations.AlterField(
            model_name='city_image',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.city'),
        ),
        migrations.AlterField(
            model_name='city_voting',
            name='item_vote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votings', to='api.city'),
        ),
        migrations.AlterField(
            model_name='city_voting',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_votings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='nation_image',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.nation'),
        ),
        migrations.AlterField(
            model_name='nation_voting',
            name='item_vote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votings', to='api.nation'),
        ),
        migrations.AlterField(
            model_name='nation_voting',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nation_votings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to='api.city'),
        ),
        migrations.AlterField(
            model_name='restaurant_image',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.restaurant'),
        ),
        migrations.AlterField(
            model_name='restaurant_voting',
            name='item_vote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votings', to='api.restaurant'),
        ),
        migrations.AlterField(
            model_name='restaurant_voting',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_votings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stay',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stays', to='api.city'),
        ),
        migrations.AlterField(
            model_name='stay_image',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stays', to='api.stay'),
        ),
        migrations.AlterField(
            model_name='stay_voting',
            name='item_vote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votings', to='api.stay'),
        ),
        migrations.AlterField(
            model_name='stay_voting',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stay_votings', to=settings.AUTH_USER_MODEL),
        ),
    ]
