# Generated by Django 3.2.7 on 2021-09-26 04:44

import api.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_restaurant_restaurantdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('attractions', djongo.models.fields.ArrayField(model_container=api.models.Attraction)),
                ('restaurants', djongo.models.fields.ArrayField(model_container=api.models.Restaurant)),
            ],
        ),
    ]
