# Generated by Django 3.2.7 on 2021-10-24 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20211022_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stay_image',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.stay'),
        ),
    ]
