# Generated by Django 3.2.7 on 2021-11-06 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_userdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attraction_review',
            old_name='review',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='blog_review',
            old_name='review',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='city_review',
            old_name='review',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='nation_review',
            old_name='review',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='restaurant_review',
            old_name='review',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='stay_review',
            old_name='review',
            new_name='text',
        ),
    ]
