# Generated by Django 3.2.7 on 2021-11-08 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20211106_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='number_voting',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blog',
            name='rating_score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='number_voting',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='city',
            name='number_voting',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='nation',
            name='number_voting',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='number_voting',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stay',
            name='number_voting',
            field=models.IntegerField(default=0),
        ),
    ]
