# Generated by Django 3.2.7 on 2021-11-14 13:22

from django.db import migrations, models
from django.db.migrations import migration


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_auto_20211108_1010"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="city_voting",
            name="item",
        ),
        migrations.RemoveField(
            model_name="city_voting",
            name="user",
        ),
        migrations.RemoveField(
            model_name="nation_voting",
            name="item",
        ),
        migrations.RemoveField(
            model_name="nation_voting",
            name="user",
        ),
        migrations.RemoveField(
            model_name="restaurant_voting",
            name="item",
        ),
        migrations.RemoveField(
            model_name="restaurant_voting",
            name="user",
        ),
        migrations.RemoveField(
            model_name="stay_voting",
            name="item",
        ),
        migrations.RemoveField(
            model_name="stay_voting",
            name="user",
        ),
        migrations.AddField(
            model_name="attraction_review",
            name="point",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="city_review",
            name="point",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="nation_review",
            name="point",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="restaurant_review",
            name="point",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="stay_review",
            name="point",
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name="Attraction_Voting",
        ),
        migrations.DeleteModel(
            name="City_Voting",
        ),
        migrations.DeleteModel(
            name="Nation_Voting",
        ),
        migrations.DeleteModel(
            name="Restaurant_Voting",
        ),
        migrations.DeleteModel(
            name="Stay_Voting",
        ),
    ]
