# Generated by Django 3.2.7 on 2021-09-25 12:31

from django.db import migrations, models
import djongo.models.fields
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedDestination',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('img_src', models.TextField()),
                ('rating', djongo.models.fields.EmbeddedField(model_container=home.models.Rating)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('stars', models.FloatField()),
                ('num_reviews', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='BlogPost',
        ),
        migrations.DeleteModel(
            name='Search',
        ),
    ]
