# Generated by Django 3.2.7 on 2021-11-23 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rcs', '0002_alter_attractionquery_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attractionquery',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attraction_recommends', to=settings.AUTH_USER_MODEL),
        ),
    ]
