# Generated by Django 3.2.7 on 2021-11-23 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20211114_1322'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rcs', '0003_alter_attractionquery_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_recommends', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StayQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stay_recommends', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StayReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.FloatField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.stay')),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='rcs.stayquery')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.FloatField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.restaurant')),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='rcs.restaurantquery')),
            ],
        ),
    ]
